/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_core_java_chapter16_userjni_UserService */

#ifndef _Included_org_core_java_chapter16_userjni_UserService
#define _Included_org_core_java_chapter16_userjni_UserService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_core_java_chapter16_userjni_UserService
 * Method:    create
 * Signature: (Ljava/lang/String;I)Lorg/core/java/chapter16/userjni/User;
 */
JNIEXPORT jobject JNICALL Java_org_core_java_chapter16_userjni_UserService_create
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_core_java_chapter16_userjni_UserService
 * Method:    print
 * Signature: (Lorg/core/java/chapter16/userjni/User;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_core_java_chapter16_userjni_UserService_print
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_core_java_chapter16_userjni_UserService
 * Method:    setFavoriteNumber
 * Signature: (Lorg/core/java/chapter16/userjni/User;IJ)V
 */
JNIEXPORT void JNICALL Java_org_core_java_chapter16_userjni_UserService_setFavoriteNumber
  (JNIEnv *, jobject, jobject, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
