/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_core_java_chapter16_JniHelloWorld */

#ifndef _Included_org_core_java_chapter16_JniHelloWorld
#define _Included_org_core_java_chapter16_JniHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_core_java_chapter16_JniHelloWorld
 * Method:    greet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_core_java_chapter16_JniHelloWorld_greet
  (JNIEnv *, jobject);

/*
 * Class:     org_core_java_chapter16_JniHelloWorld
 * Method:    sum
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_core_java_chapter16_JniHelloWorld_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_core_java_chapter16_JniHelloWorld
 * Method:    greetTo
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_core_java_chapter16_JniHelloWorld_greetTo
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
