// Automatically generated by org.core.java.chapter11.source.ToStringAnnotationProcessor
package org.core.java.chapter11.source;
public class ToStrings {
    public static String toString(org.core.java.chapter11.source.Point obj) {
        StringBuilder result = new StringBuilder();
        result.append("[");
        result.append(toString(obj.getX()));
        result.append(",");
        result.append(toString(obj.getY()));
        result.append("]");
        return result.toString();
    }
    public static String toString(org.core.java.chapter11.source.Rectangle obj) {
        StringBuilder result = new StringBuilder();
        result.append("org.core.java.chapter11.source.Rectangle");
        result.append("[");
        result.append(toString(obj.getTopLeft()));
        result.append(",");
        result.append("width=");
        result.append(toString(obj.getWidth()));
        result.append(",");
        result.append("height=");
        result.append(toString(obj.getHeight()));
        result.append("]");
        return result.toString();
    }
    public static String toString(Object obj) {
        return java.util.Objects.toString(obj);
    }
}
